services:
#  web:
#    image: maven:3.9.2-eclipse-temurin-17-focal
#    command: mvn spring-boot:run
#    working_dir: /app
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app
#    depends_on:
#      - db
  db:
    hostname: mysqlserver
    container_name: banco
    image: mysql:8.0.33
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: meudb
