CREATE TABLE `meudb`.`ENDERECO`
(
    ID_ENDERECO         BIGINT NOT NULL AUTO_INCREMENT,
    ESTADO              VARCHAR(2),
    CIDADE              VARCHAR(100),
    BAIRRO              VARCHAR(100),
    RUA                 VARCHAR(100),
    NUMERO              INT,
    PRIMARY KEY (ID_ENDERECO)
);
CREATE TABLE `meudb`.`TELEFONE`
(
    ID_TELEFONE         BIGINT NOT NULL AUTO_INCREMENT,
    FIXO                VARCHAR(15),
    CELULAR             VARCHAR(15),
    PRIMARY KEY (ID_TELEFONE)
);

CREATE TABLE `meudb`.`TIPO_SANGUINEO`
(
    id_tipo_sanguineo   BIGINT NOT NULL AUTO_INCREMENT,
    sorotipagem         VARCHAR(3),
    PRIMARY KEY (id_tipo_sanguineo)
);

CREATE TABLE `meudb`.`DOACAO`
(
    ID_DOACAO                   BIGINT NOT NULL AUTO_INCREMENT,
    ID_TIPO_SANGUINEO_DOADOR    BIGINT NOT NULL,
    ID_TIPO_SANGUINEO_RECEPTOR  BIGINT NOT NULL,
    PRIMARY KEY (ID_DOACAO),
    CONSTRAINT FK_DOACAO_TIPO_SANGUINEO_DOADOR FOREIGN KEY (ID_TIPO_SANGUINEO_DOADOR) REFERENCES TIPO_SANGUINEO(id_tipo_sanguineo),
    CONSTRAINT FK_DOACAO_TIPO_SANGUINEO_RECEPTOR FOREIGN KEY (ID_TIPO_SANGUINEO_RECEPTOR) REFERENCES TIPO_SANGUINEO(id_tipo_sanguineo)
);

CREATE TABLE `meudb`.`PESSOAS`
(
    ID_PESSOA                   BIGINT NOT NULL AUTO_INCREMENT,
    NOME                        VARCHAR(100),
    CPF                         VARCHAR(11),
    RG                          VARCHAR(12),
    DATA_NASC                   DATE,
    SEXO                        VARCHAR(9),
    MAE                         VARCHAR(100),
    PAI                         VARCHAR(100),
    ALTURA                      FLOAT,
    PESO                        FLOAT,
    ID_TIPO_SANGUINEO           BIGINT NOT NULL,
    ID_ENDERECO                 BIGINT NOT NULL,
    ID_TELEFONE                 BIGINT NOT NULL,
    PRIMARY KEY (ID_PESSOA),
    CONSTRAINT FK_TIPO_SANGUINEO FOREIGN KEY (ID_TIPO_SANGUINEO) REFERENCES TIPO_SANGUINEO(id_tipo_sanguineo),
    CONSTRAINT FK_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO),
    CONSTRAINT FK_TELEFONE FOREIGN KEY (ID_TELEFONE) REFERENCES TELEFONE(ID_TELEFONE)
);



